services:
  db:
    container_name: elasticsearch
    image: elasticsearch:8.19.4
    restart: always
    ports:
      - 9400:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:
    external: false
